name : RAG CI

# Trigger the worklows for any push to main branch or pull request

on:
    push:
        branches:
            - main
            - streamlit
    pull_request:
        branches:
            - main
            - streamlit



jobs:
    test:
        runs-on: ubuntu-latest

        env:
            DATABASEURL : ${{ secrets.DATABASE_URL }}
            GROQ_API_KEY : ${{ secrets.GROQ_API_KEY}}
            OPENROUTER_API_KEY : ${{secrets.OPENROUTER_API_KEY}}

        steps:
            # Step 1 : check out the code from the repository
            - name : check out code
            uses: actions/checkout@v4
            
            # step 2 : set up python
            - name : Set up Python
            uses : actions/setup-python@v5
            with :
                python-version : '3.12'
            
            # Step 3 : Install uv
            - name : Install uv
            uses: astral-sh/setup-uv@v3
            # step  3 : install uv env
            - name : Install UV
            run : uv sync

            - name : Run tests
            run : uv run pytest
            
